List<String> names = [
  'Test One',
  'Test Two',
  'Test Three',
  'Test Four',
  'Test Five',
  'Test Six',
  'Test Seven',
  'Test Eight',
  'Test Nine',
  'Test Ten',
  'Test Eleven',
  'Test Twelve',
  'Test Thirteen',
  'Test Fourteen',
  'Test Fifteen',
  'Test Sixteen',
  'Test Seventeen',
  'Test Eighteen',
  'Test Nineteen',
  'Test Twenty',
];

List<String> roles = [
  "Product Designer",
  "Flutter Developer",
  "QA Tester",
  "Product Owner"
];

DateTime now = DateTime.now();
List<DateTime> startDates = [
  now.subtract(const Duration(days: 1)),
  now.subtract(const Duration(days: 2)),
  now.subtract(const Duration(days: 3)),
  now.subtract(const Duration(days: 4)),
  now.subtract(const Duration(days: 5)),
  now.subtract(const Duration(days: 6)),
  now.subtract(const Duration(days: 7)),
  now.subtract(const Duration(days: 9)),
  now.subtract(const Duration(days: 10)),
  now.subtract(const Duration(days: 11)),
  now.subtract(const Duration(days: 12)),
  now.subtract(const Duration(days: 13)),
  now.subtract(const Duration(days: 14)),
  now.subtract(const Duration(days: 15)),
  now.subtract(const Duration(days: 16)),
  now.subtract(const Duration(days: 17)),
  now.subtract(const Duration(days: 18)),
  now.subtract(const Duration(days: 19)),
  now.subtract(const Duration(days: 20)),
];

List<DateTime?> endDates = [
  null,
  now.add(const Duration(days: 2)),
  now.add(const Duration(days: 3)),
  null,
  now.add(const Duration(days: 5)),
  null,
  null,
  now.add(const Duration(days: 9)),
  null,
  now.add(const Duration(days: 11)),
  null,
  null,
  null,
  now.add(const Duration(days: 15)),
  now.add(const Duration(days: 16)),
  null,
  now.add(const Duration(days: 18)),
  now.add(const Duration(days: 19)),
  now.add(const Duration(days: 20)),
];
